// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'stripcard';
  static const String PROJECT_VERSION = '4.1.0+15';
  static const String AGENCYFB_BOLD = 'AgencyFB-Bold';
}
